name: "airbnb_sydney_dw"
version: "1.0.0"
config-version: 2

profile: "airbnb_sydney"

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

# Settings
# seeds:
#   airbnb_sydney_dw:
#     +schema: bronze
#     +quote_columns: false

models:
  airbnb_sydney_dw:
    +materialized: table

    staging:
      +schema: staging
      +materialized: table

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table

    datamart:
      +schema: datamart
      +materialized: view