name: 'airbnb_sydney_dw'
version: '1.0.0'
config-version: 2

profile: 'airbnb_sydney'

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbnb_sydney_dw:
    +materialized: view

  staging:
    +schema: staging
    +materialized: table

  silver:
    +schema: silver
    +materialized: table

  gold:
    +schema: dwh_gold
    +materialized: table

  datamart:
    +schema: dwh_datamart
    +materialized: view
