# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'airbnb_sydney_dw'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'airbnb_sydney'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  # The project name acts as the top-level configuration block
  airbnb_sydney_dw: 
    # Default schema and materialization for all models unless overridden
    staging:
      +schema: staging
      +materialized: table
    # Configuration for Silver layer models (e.g., stg_*, snapshots)
    silver: 
      +schema: silver
      +materialized: table
    # Configuration for Gold layer models (Facts, Dimensions, Reference)
    gold:
      +schema: dwh_gold # FIX: Use a unique name to avoid schema inheritance issue
      +materialized: table
    # Configuration for Datamart views (MUST be views)
    datamart:
      +schema: dwh_datamart
      +materialized: view