version: 2

sources:
  - name: bronze
    schema: bronze # Postgres schema where Airflow loads the data
    tables:
      - name: airbnb_listings_raw # Postgres table name
      - name: census_g01_raw
      - name: census_g02_raw
      - name: nsw_lga_code_raw
      - name: nsw_lga_suburb_raw
  - name: materialized_gold
    schema: silver_gold # The actual schema where dbt materialized the fact table
    tables:
      - name: fact_airbnb_revenue