version: 2

sources:
    - name: bronze
      schema: bronze
      tables:
        - name: airbnb_listings_raw
        - name: airbnb_hosts_raw
        - name: census_g01_raw
        - name: census_g02_raw
        - name: nsw_lga_code_raw
        - name: nsw_lga_suburb_raw